
package org.sforce.soap._2005._09.outbound;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Notification Service Implementation
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "NotificationService", targetNamespace = "http://soap.sforce.com/2005/09/outbound", wsdlLocation = "file:/D:/srikanth-javaprojects/salesforce/client.wsdl")
public class NotificationService
    extends Service
{

    private final static URL NOTIFICATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.sforce.soap._2005._09.outbound.NotificationService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.sforce.soap._2005._09.outbound.NotificationService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/srikanth-javaprojects/salesforce/client.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/srikanth-javaprojects/salesforce/client.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NOTIFICATIONSERVICE_WSDL_LOCATION = url;
    }

    public NotificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationService() {
        super(NOTIFICATIONSERVICE_WSDL_LOCATION, new QName("http://soap.sforce.com/2005/09/outbound", "NotificationService"));
    }

    /**
     * 
     * @return
     *     returns NotificationPort
     */
    @WebEndpoint(name = "Notification")
    public NotificationPort getNotification() {
        return super.getPort(new QName("http://soap.sforce.com/2005/09/outbound", "Notification"), NotificationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationPort
     */
    @WebEndpoint(name = "Notification")
    public NotificationPort getNotification(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.sforce.com/2005/09/outbound", "Notification"), NotificationPort.class, features);
    }

}
