<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <outboundMessages>
        <fullName>RetriveMetadataForClient</fullName>
        <apiVersion>34.0</apiVersion>
        <endpointUrl>https://sfinfraws.herokuapp.com/retrieveclient</endpointUrl>
        <fields>BaseOrgId__c</fields>
        <fields>BaseOrgRefreshToken__c</fields>
        <fields>BaseOrgToken__c</fields>
        <fields>BaseOrgUrl__c</fields>
        <fields>ID__c</fields>
        <fields>Id</fields>
        <fields>OrganizationId__c</fields>
        <fields>RecordId__c</fields>
        <fields>SourceOrgRefreshToken__c</fields>
        <fields>SourceOrgToken__c</fields>
        <fields>SourceOrganizationURL__c</fields>
        <fields>TargetOrgRefreshToken__c</fields>
        <fields>TargetOrgTokenNonEncrypted__c</fields>
        <fields>TargetOrgToken__c</fields>
        <includeSessionId>false</includeSessionId>
        <integrationUser></integrationUser>
        <name>RetriveMetadataForClient</name>
        <protected>false</protected>
        <useDeadLetterQueue>false</useDeadLetterQueue>
    </outboundMessages>
    <rules>
        <fullName>OutboundRetrieveMetadataForClient</fullName>
        <actions>
            <name>RetriveMetadataForClient</name>
            <type>OutboundMessage</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>MetadataLogInformation__c.Action__c</field>
            <operation>equals</operation>
            <value>Retrieve</value>
        </criteriaItems>
        <criteriaItems>
            <field>MetadataLogInformation__c.Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
</Workflow>
